// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKD2fGob2z_0KQ5o4mTGE8QGh2vnO9ouk',
    appId: '1:267212425896:web:1dad1efa7cb8e1f9b6109d',
    messagingSenderId: '267212425896',
    projectId: 'store-app-f755e',
    authDomain: 'store-app-f755e.firebaseapp.com',
    storageBucket: 'store-app-f755e.appspot.com',
    measurementId: 'G-K1H96YPTJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO9Q6aiunHclDHWZhrdLrWTgl4ZQUg4As',
    appId: '1:267212425896:android:a547e9ba2a3ca44db6109d',
    messagingSenderId: '267212425896',
    projectId: 'store-app-f755e',
    storageBucket: 'store-app-f755e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_mmC8VhoJhoL_ep4oDV7dZXtf1VKVQQ',
    appId: '1:267212425896:ios:2809fbb294ce1288b6109d',
    messagingSenderId: '267212425896',
    projectId: 'store-app-f755e',
    storageBucket: 'store-app-f755e.appspot.com',
    iosClientId: '267212425896-4sv1e05t6kqprppa00c6otlq7ojhvk9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_mmC8VhoJhoL_ep4oDV7dZXtf1VKVQQ',
    appId: '1:267212425896:ios:2809fbb294ce1288b6109d',
    messagingSenderId: '267212425896',
    projectId: 'store-app-f755e',
    storageBucket: 'store-app-f755e.appspot.com',
    iosClientId: '267212425896-4sv1e05t6kqprppa00c6otlq7ojhvk9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
